spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment-planner?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sys123457!

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

server:
  port: 8084